version: '3.8'

services:
  postgres:
    image: postgres
    container_name: Exam
    environment:
      POSTGRES_DB: exam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"