version: '3.8'

services:
  #  postgres:
  #    image: postgres
  #    restart: unless-stopped
  #    container_name: Exam_DB
  #    environment:
  #      POSTGRES_DB: exam_db
  #      POSTGRES_USER: teach1
  #      POSTGRES_PASSWORD: donetoNTC
  #    ports:
  #      #            - "5435:5432"
  #      - "5432:5432"

  app:
    build: .
    container_name: Exam_App
    #    depends_on:
    #      - postgres
    ports:
      - "8181:8181"
    volumes:
      - uploads_volume:/app/uploads/
    command: [ "java", "-jar", "app.jar"]
#    command: ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]

volumes:
  uploads_volume:
